# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-SafeInclude
version:      0.02
version_from: lib/Template/Plugin/SafeInclude.pm
installdirs:  site
requires:
    parent:                        0
    Test::More:                    0
    version:                       0
    Template::Plugin:               0
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
